name: ai_recipe_generation
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  camera: ^0.10.6
  cloud_firestore: ^5.4.5
  device_info_plus: ^9.1.2
  firebase_core: ^3.7.0
  flutter_floating_bottom_bar: ^1.2.1
  flutter_markdown: ^0.7.4
  flutter_svg: ^2.0.14
  google_fonts: 6.2.1
  google_generative_ai: ^0.4.6
  image_picker: ^1.1.2
  material_symbols_icons: ^4.2791.1
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  sticky_headers: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
